### ISSUE TITLE
Userideas VOTE

### ISSUE THREAD

**Issue by Yorkieee** [ITPrism/UserIdeas#16]
I have installed Userideas on Joomla 3 and It works really well except voting. I have downloaded and enabled all required plug ins. I think it is nearly there but can not work the vote button from the items and view screen.

So far I tried to modify a line which is for the vote button contains 'href="javascript: void(0);' in default.php in tmpl folder under /components/com_userideas/views/items. 

I have a userideavote folder under /plugins/system.  The folder contains userideasvote.php and votebutton.js. I expect if I could call the extend plugin, it would work.  Anyone had a same issue?

**Comment by ITPrism** [comment]
Hi,
OMG! Dude, please do not publish password for your website on public servers. :)

I have just checked the problem. It seems, it is missing a column "_**hash**_" in table '_**#__uideas_votes**_'.

Unknown column 'a.hash' in 'where clause'
You can find the error in _**/log/jcontroller.log.php**_.

You have to install the new version over the old one when upgrade the extension. And the system will create newest columns automatically.
I think about two solutions.

Install old version of User Ideas. You can install 1.5.
After that, install last version over release 1.5. The system will create the column "hash".

Alternatively, you can create the column manually via your PHPMyAdmin.

Here you are the query.
ALTER TABLE `#__uideas_votes` ADD `hash` VARCHAR( 32 ) NULL DEFAULT NULL COMMENT 'Anonymous users hash.' AFTER `user_id` ;

Best regards,
Todor

**Comment by brijeshguru99** [comment]
Thank you very much for your solution.Its working.thanks again

**Comment by Jdmds** [comment]
I also cannot get the vote button to work. Have tried the above (except loading 1.5 as I can't find it) with no success. Also, the author always shows anonymous, Is this related to the voting not working?

**Comment by ITPrism** [comment]
Hi,
Check for JavaScript error or enable the plugins that include vote functionality.

About the anonymous user, it was the bug that I fixed. I am going to publish the new version.

Cheers.
