### ISSUE TITLE
White Screen after installation accessing User Ideas component from administration

### ISSUE THREAD

**Issue by ethyrie** [ITPrism/UserIdeas#29]
Installed User Ideas in my Joomla 3.4.4 site
It noticed me I had to install ITPrism Library
I installed it and went to the extensions manager, and activated (published) the User Ideas elements

Now when I try to access User Ideas administration page I get a white sad screen

**Comment by ethyrie** [comment]
Sorry I activated the joomla error reports and this is showing up
Fatal error: Class 'UserIdeas\Version' not found in /"dir"/administrator/components/com_userideas/views/dashboard/view.html.php on line 44

**Comment by ITPrism** [comment]
Hi,
Could you rename the library from **/libraries/userideas** to **/libraries/UserIdeas**?

Let we see what will happen.

**Comment by ITPrism** [comment]
I have just fixed the bug. You can [download User Ideas] (http://itprism.com/free-joomla-extensions/ecommerce-gamification/feedbacks-ideas-suggestions) and [upgrade] (http://itprism.com/help/108-userideas-documentation-faq#upgrade) to v2.1.

**Comment by ethyrie** [comment]
Thanks a LOT!
I was expecting that it was my failure
I thought about the case of the letters too, I noticed every extension in my installation had low-case names so It was pretty obvious, just don't trust myself :P
Installing!

**Comment by ethyrie** [comment]
I can confirm now this is fixed in User Ideas 2.1
Great :D
