### ISSUE TITLE
Re-Installation not working properly

### ISSUE THREAD

**Issue by ethyrie** [ITPrism/UserIdeas#30]
When you try to install UserIdeas component after you had the component uninstalled this error occurs:

Advertencia
Multiple primary key defined SQL=ALTER TABLE `web_uideas_comments` ADD PRIMARY KEY (`id`), ADD KEY `idx_ui_comment_record_date` (`record_date`), ADD KEY `idx_ui_comment_item_published` (`item_id`,`published`);

Paquete Instalar: Se produjo un error instalando la extensión: com_userideas.zip

The solution is to manually erase the tables of the database so the component can create them again (It works for me)

I think that it would be easely fixed dropping the tables at uninstall but I'm still not sure of how that part of Joomla! works. 

Other way to fixing it would be to include the ability to install the component again over the already-created tables and put the UserIdeas version somewhere in the DB, include the updates in the script, and apply the ones needed

Thanks for your awesome work

**Comment by ITPrism** [comment]
you have to remove the tables manually. The prefix of the tables is uideas_
You can use phpMyAdmin to do that.

**Comment by ITPrism** [comment]
I moved the creation of indexes in table construction. Now, it will be OK.
You can download and install the package without errors.

**Comment by ethyrie** [comment]
I already did that with the mysql console but thanks!
