### ISSUE TITLE
Fatal Error:  Call to undefined method Userideas\Status\Statuses::getStatusesOptions

### ISSUE THREAD

**Issue by marcodeluca** [ITPrism/UserIdeas#36]
Updated your component with your latest release and have a fatal error. 

Fatal error: Call to undefined method Userideas\Status\Statuses::getStatusesOptions() in /var/www/blah/blah/modules/mod_userideassearch/mod_userideassearch.php on line 46

`$statusesOptions = $statuses->getStatusesOptions();`

If I comment it out I can load the component but then you have undefined vars of course:
`
Notice: Undefined variable: statusesOptions in /var/www/blah/blah/modules/mod_userideassearch/mod_userideassearch.php on line 51`

`Warning: array_merge(): Argument #2 is not an array in /var/www/blah/blah/modules/mod_userideassearch/mod_userideassearch.php on line 51`

**Comment by ITPrism** [comment]
Which version of the module UserIdeas Search do you use?
I guess, you will have to upgrade the module. 
You can download it from the member site.
https://members.itprism.com/membership/premium-extensions/category/5-user-ideas-pro

**Comment by marcodeluca** [comment]
Yes updating worked. Watch out I think you have some undefined language strings:

MOD_USERIDEASSEARCH_ALPHABETICALLY
MOD_USERIDEASSEARCH_MOST_VOTED
MOD_USERIDEASSEARCH_LATEST
MOD_USERIDEASSEARCH_MOST_POPULAR
![screen shot 2016-11-22 at 8 04 38 am](https://cloud.githubusercontent.com/assets/968926/20524824/5c813182-b08a-11e6-82c9-8f840fa2c094.png)

**Comment by ITPrism** [comment]
Is it overridden view? 
I changed those constants in last release. Your layout shows old language constants. You will have to edit the layout that you use to override the module view.

**Comment by marcodeluca** [comment]
You're right again. Thanks:)
