### ISSUE TITLE
Wrong Option Tabs on Configuration Page After Update

### ISSUE THREAD

**Issue by jsiepka** [ITPrism/UserIdeas#39]
After updating Joomla from 3.4 to 3.6.5, UserIdeas 2.4 and Prism Library Version 1.18 I cannot view or change UserIdeas settings as the incorrect tabs are displayed on the Configuration Page. Please See attached screen shot.
[UserIdeas ScreenShot.pdf](https://github.com/ITPrism/UserIdeas/files/790721/UserIdeas.ScreenShot.pdf)

**Comment by jsiepka** [comment]
I found where my confusion was. The documentation does not match the current version and the documentation is not clear on all options.  Hopefully you may have time to update the documentation on such a good extension.

**Comment by ITPrism** [comment]
You are right. Thank you!
I am going to update the documentation.
